version: '3'

services:
    database:
        image: postgres:${POSTGRES_VERSION:-14}-alpine
        ports:
            - ${POSTGRES_EXTERNAL_PORT}:5432
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - db-data:/var/lib/postgresql/data:rw
    php:
        build:
            context: .
            dockerfile: docker/php/dev.Dockerfile
            args:
                LINUX_USER_ID: ${LINUX_USER_ID}
        environment:
            XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_REMOTE_PORT}
            PHP_IDE_CONFIG: serverName=${IDE_SERVER_NAME}
        volumes:
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./:/srv/app
            - ./.env:/srv/app/.env
        depends_on:
            - database
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/dev.Dockerfile
            args:
                NGINX_PORT: ${NGINX_BACKEND_PORT}
        volumes:
            - ./public/:/srv/app/public
        depends_on:
            - php
        ports:
            - ${NGINX_BACKEND_PORT}:${NGINX_BACKEND_PORT}
volumes:
    db-data:
